namespace RelayBench.Core.Models;

public sealed record PortScanResult(
    DateTimeOffset CheckedAt,
    bool IsEngineAvailable,
    string EngineName,
    string EngineVersion,
    string Target,
    string ProfileKey,
    string ProfileName,
    string CustomPortsText,
    string EffectivePortsText,
    string CommandLine,
    bool ScanExecuted,
    bool ScanSucceeded,
    int? ExitCode,
    int OpenPortCount,
    int OpenEndpointCount,
    int AttemptedEndpointCount,
    IReadOnlyList<string> ResolvedAddresses,
    IReadOnlyList<PortScanFinding> Findings,
    string Summary,
    string? Error,
    string StandardOutput,
    string StandardError,
    IReadOnlyList<string>? SystemResolvedAddresses = null);
