namespace RelayBench.Core.Models;

public sealed record ProxyProbeScenarioResult(
    ProxyProbeScenarioKind Scenario,
    string DisplayName,
    string CapabilityStatus,
    bool Success,
    int? StatusCode,
    TimeSpan? Latency,
    TimeSpan? FirstTokenLatency,
    TimeSpan? Duration,
    bool ReceivedDone,
    int ChunkCount,
    bool? SemanticMatch,
    string Summary,
    string? Preview,
    ProxyFailureKind? FailureKind,
    string? FailureStage,
    string? Error,
    IReadOnlyList<string>? ResponseHeaders = null,
    int? OutputTokenCount = null,
    bool OutputTokenCountEstimated = false,
    int? OutputCharacterCount = null,
    TimeSpan? GenerationDuration = null,
    double? OutputTokensPerSecond = null,
    double? EndToEndTokensPerSecond = null,
    int OutputTokensPerSecondSampleCount = 1,
    double? MaxChunkGapMilliseconds = null,
    double? AverageChunkGapMilliseconds = null,
    string? RequestId = null,
    string? TraceId = null,
    ProxyProbeTrace? Trace = null);
