namespace NetTest.Core.Models;

public sealed record ProxyStabilityResult(
    DateTimeOffset CheckedAt,
    string BaseUrl,
    int RequestedRounds,
    int CompletedRounds,
    int DelayMilliseconds,
    int FullSuccessCount,
    int ModelsSuccessCount,
    int ChatSuccessCount,
    int StreamSuccessCount,
    int MaxConsecutiveFailures,
    double FullSuccessRate,
    double ModelsSuccessRate,
    double ChatSuccessRate,
    double StreamSuccessRate,
    TimeSpan? AverageChatLatency,
    TimeSpan? AverageStreamFirstTokenLatency,
    int HealthScore,
    string HealthLabel,
    string Summary,
    IReadOnlyList<ProxyDiagnosticsResult> RoundResults,
    int ResponsesSuccessCount = 0,
    int StructuredOutputSuccessCount = 0,
    TimeSpan? AverageResponsesLatency = null,
    TimeSpan? AverageStructuredOutputLatency = null,
    IReadOnlyList<ProxyFailureDistributionItem>? FailureDistributions = null,
    string? FailureDistributionSummary = null,
    int DistinctResolvedAddressCount = 0,
    int DistinctEdgeSignatureCount = 0,
    int EdgeSwitchCount = 0,
    string? CdnStabilitySummary = null);
