namespace NetTest.Core.Models;

public sealed record ProxyThroughputBenchmarkResult(
    DateTimeOffset CheckedAt,
    string BaseUrl,
    string Model,
    int RequestedSampleCount,
    int CompletedSampleCount,
    int SuccessfulSampleCount,
    int SegmentCount,
    double? MedianOutputTokensPerSecond,
    double? AverageOutputTokensPerSecond,
    double? MinimumOutputTokensPerSecond,
    double? MaximumOutputTokensPerSecond,
    double? MedianEndToEndTokensPerSecond,
    int? AverageOutputTokenCount,
    bool OutputTokenCountEstimated,
    string Summary,
    string? Error,
    IReadOnlyList<ProxyStreamingStabilityResult> Samples,
    string? RequestId = null,
    string? TraceId = null,
    bool IsLive = false,
    int CurrentSampleIndex = 0,
    TimeSpan? CurrentSampleElapsed = null,
    int? CurrentOutputTokenCount = null,
    bool CurrentOutputTokenCountEstimated = false,
    double? CurrentOutputTokensPerSecond = null,
    double? CurrentEndToEndTokensPerSecond = null);
