namespace NetTest.Core.Models;

public sealed record ProxyDiagnosticsResult(
    DateTimeOffset CheckedAt,
    string BaseUrl,
    string RequestedModel,
    string? EffectiveModel,
    bool ModelsRequestSucceeded,
    int? ModelsStatusCode,
    int ModelCount,
    IReadOnlyList<string> SampleModels,
    TimeSpan? ModelsLatency,
    bool ChatRequestSucceeded,
    int? ChatStatusCode,
    TimeSpan? ChatLatency,
    string? ChatPreview,
    bool StreamRequestSucceeded,
    int? StreamStatusCode,
    TimeSpan? StreamFirstTokenLatency,
    TimeSpan? StreamDuration,
    string? StreamPreview,
    string Summary,
    string? Error,
    IReadOnlyList<ProxyProbeScenarioResult>? ScenarioResults = null,
    ProxyFailureKind? PrimaryFailureKind = null,
    string? PrimaryFailureStage = null,
    string? Verdict = null,
    string? Recommendation = null,
    string? PrimaryIssue = null,
    string? ResponseHeadersSummary = null,
    IReadOnlyList<string>? ResolvedAddresses = null,
    string? CdnProvider = null,
    string? EdgeSignature = null,
    string? CdnSummary = null,
    ProxyStreamingStabilityResult? LongStreamingResult = null,
    string? RequestId = null,
    string? TraceId = null,
    string? TraceabilitySummary = null);
